# Jekyll configuration for Open SDG platform
#
# You will need to change all of the capitalized variables below according
# to your Github setup. For example, if your site and data repositories are:
# -- https://github.com/my-awesome-github-org/my-awesome-site-repo
# -- https://github.com/my-awesome-github-org/my-awesome-data-repo
# Then you would want to make these replacements throughout this file:
# -- replace "MY-GITHUB-ORG" with "my-awesome-github-org"
# -- replace "OPEN-SDG-SITE-STARTER" with "my-awesome-site-repo"
# -- replace "OPEN-SDG-DATA-STARTER" with "my-awesome-data-repo"

# Replace this title as needed.
title: City of Los Angeles Indicators For The Sustainable Development Goals
# Replace the baseurl with the name of this repository.
baseurl: "/open-sdg-site-starter"
url: ""
data_dir: data
environment: staging
# Replace MY-GITHUB-ORG and OPEN-SDG-DATA-STARTER as needed.
remotedatabaseurl: "https://d26ib27epzwu9e.cloudfront.net"

jekyll_get_json:
  - data: meta
    # Replace MY-GITHUB-ORG and OPEN-SDG-DATA-STARTER as needed.
    json: 'https://d26ib27epzwu9e.cloudfront.net/meta/all.json'
  - data: headlines
    # Replace MY-GITHUB-ORG and OPEN-SDG-DATA-STARTER as needed.
    json: 'https://d26ib27epzwu9e.cloudfront.net/headline/all.json'
  - data: schema
    # Replace MY-GITHUB-ORG and OPEN-SDG-DATA-STARTER as needed.
    json: 'https://d26ib27epzwu9e.cloudfront.net/meta/schema.json'
  - data: reporting
    json: 'https://d26ib27epzwu9e.cloudfront.net/stats/reporting.json'
  - data: translations
    json: 'https://open-sdg.github.io/sdg-translations/translations-0.5.1.json'

#Defualt DATA CloudFront AWS Control Tower Dev 
#d26ib27epzwu9e.cloudfront.net

analytics:
  ga_prod: ''

# Social media accounts.
twitter: 'MyTwitterAccount'

# Replace the email addresses below.
email_contacts:
  questions: sdg@lacity.org
  suggestions: sdg@lacity.org
  functional: sdg@lacity.org

# Github Repo for Data
# Replace this value as needed.
repo_name: open-sdg-data-starter
branch: develop
# Replace this value as needed.
org_name: dawncomer

# Build settings
markdown: kramdown

# Travis Support
exclude: [vendor, scripts, remotedata]

# International Support
# Eg name: Australia and adjective: Australian
country:
  name: City of Los Angeles
  adjective: Angeleno

# Pages
collections:
  pages:
    output: true
    permalink: /:path/
  posts:
    output: true
    permalink: /news/:year/:month/:day/:title.html
  indicators:
    output: true
  goals:
    output: true

# Menu
menu:
  # Use these to customise the main navigation.
  - path: /
    translation_key: general.goals
  - path: /reporting-status
    # The "translation_key" refers to the key in the SDG Translations repository.
    translation_key: data summary
  - path: /publications/
    translation_key: menu.publications 
  - path: /about
    translation_key: menu.about

# Configure the text (or "translation key") to be used on the
# non-global metadata tab.
non_global_metadata: Local Metadata

# The list of languages that are translated. The first one is the default.
languages:
  - en

# This makes sure that all pages have a language.
defaults:
  -
    scope:
      path: ""
    values:
      language: "en"

# Set where to point to for goal images.
goal_image_base: https://open-sdg.github.io/sdg-translations/assets/img/goals

# Tell Jekyll to use the Remote Theme plugin.
plugins:
  - jekyll-remote-theme
  - jekyll-get-json
  - jekyll-open-sdg-plugins

# Tell the Remote Theme plugin to use the Open SDG platform (Jekyll theme).
remote_theme: brockfanning/open-sdg@chartjs-component-cleanup

# Apply any custom CSS.
custom_css:
  - /assets/css/custom.css
